name: booktrack
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  intl_translation: 0.18.0
  fl_chart: ^0.64.0 
  table_calendar: ^3.0.8
  easy_pie_chart: ^1.0.1
  flutter_svg: ^2.0.0
  
  carousel_slider: ^5.0.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  charts_flutter: ^0.12.0
  shared_preferences: ^2.5.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lib/pages/

  
  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: fonts/MPLUSRounded1c-Bold.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: MyFlutter
      fonts:
        - asset: fonts/MyFlutter.ttf